name: emergency_app
description: "A new Flutter project."
version: 1.0.0+1


environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  provider: ^6.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  video_player: ^2.9.2
  permission_checker: ^0.0.2
  permission_handler: ^11.3.1
  http: ^1.3.0
  device_info_plus: ^10.1.2
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true